server:
  port: 8761
eureka:
  instance:
    instance-id: REGISTRY-SERVICE
  client:
    register-with-eureka: false
    fetch-registry: false
  renewalPercentThreshold: 0.85
spring:
  application:
    name: REGISTRY-SERVICE