server:
  port: 8761
eureka:
  instance:
    hostname: registry-service-production.up.railway.app/eureka/
  client:
    register-with-eureka: false
    fetch-registry: false
  renewalPercentThreshold: 0.85
spring:
  application:
    name: REGISTRY-SERVICE